# SPDX-License-Identifier: Apache-2.0
"""T7 — tamper states on the capsule verify surface.

Loads the four pinned ``test-vectors/tamper-states/`` bundles and asserts the
real ritual evaluator (``hosted_profiles.aac.evaluate_ritual``) produces exactly
the stage statuses recorded in each fixture's ``expected.json`` (itself
generated by running the same evaluator — see
``scripts/generate_tamper_state_vectors.py``).

Mutant checks: for the two structural failure vectors (digest_mismatch,
chain_gap), un-tampering the fixture must flip the corresponding stage back
to "pass" — this is the check-fails-its-mutant guardrail.
"""
from __future__ import annotations

import json
from pathlib import Path

from hosted_profiles import aac

VECTORS_DIR = Path(__file__).resolve().parents[1] / "test-vectors" / "tamper-states"


def _load(name: str) -> tuple[list[dict], dict | None, dict, dict]:
    vec_dir = VECTORS_DIR / name
    bundle_doc = json.loads((vec_dir / "bundle.json").read_text())
    expected = json.loads((vec_dir / "expected.json").read_text())
    return bundle_doc["bundle"], bundle_doc.get("witness"), expected, bundle_doc.get("disclosures") or {}


def _stage(summary_stages, name):
    return next(s for s in summary_stages if s.name == name)


def _run(bundle, witness, disclosures=None):
    disclosures = disclosures or {}
    views = [
        aac.parse_capsule({"capsule": c, "disclosures": disclosures[c["capsule_id"]]})
        if c.get("capsule_id") in disclosures
        else aac.parse_capsule(c)
        for c in bundle
    ]
    return aac.evaluate_ritual(bundle, views, witness=witness), views


# ---------------------------------------------------------------------------
# digest_mismatch
# ---------------------------------------------------------------------------

def test_digest_mismatch_integrity_fails_and_is_the_finding():
    bundle, witness, expected, disclosures = _load("digest_mismatch")
    summary, _ = _run(bundle, witness, disclosures)
    assert _stage(summary.stages, "Integrity").status == "fail"
    assert _stage(summary.stages, "Sequence").status == "pass"
    assert summary.finding is not None
    assert summary.finding.code == "digest_mismatch"
    assert expected["finding"]["code"] == "digest_mismatch"


def test_digest_mismatch_downstream_record_flagged_not_failed():
    bundle, witness, _, disclosures = _load("digest_mismatch")
    _, views = _run(bundle, witness, disclosures)
    notes = aac.annotate_records(bundle, views)
    assert notes[1].note == "digest_mismatch"
    assert notes[1].is_altered is True
    # record 2 chains to the altered record 1 — it verifies itself, but is flagged
    assert notes[2].note == "cites an altered record"
    assert notes[2].is_altered is False
    assert notes[2].cites_altered is True


def test_digest_mismatch_mutant_check():
    """The check must FAIL its mutant: un-tamper the disclosed payload and Integrity flips to pass."""
    bundle, witness, _, disclosures = _load("digest_mismatch")
    fixed_disclosures = json.loads(json.dumps(disclosures))  # deep copy
    capsule_id = bundle[1]["capsule_id"]
    fixed_disclosures[capsule_id]["agent_input"] = {"tool": "refund", "amount_usd": 1180}  # matches the committed digest
    summary, _ = _run(bundle, witness, fixed_disclosures)
    assert _stage(summary.stages, "Integrity").status == "pass"
    assert summary.finding is None


# ---------------------------------------------------------------------------
# chain_gap
# ---------------------------------------------------------------------------

def test_chain_gap_sequence_fails_and_is_the_finding():
    bundle, witness, expected, _ = _load("chain_gap")
    summary, _ = _run(bundle, witness)
    assert _stage(summary.stages, "Integrity").status == "pass"
    assert _stage(summary.stages, "Sequence").status == "fail"
    assert summary.finding is not None
    assert summary.finding.code == "chain_gap"
    assert expected["gaps"], "fixture must document the gap window"
    gap = expected["gaps"][0]
    assert gap["before_index"] == 1 and gap["after_index"] == 2


def test_chain_gap_mutant_check():
    """Un-break the chain (point at the real prior capsule) and Sequence flips to pass."""
    bundle, witness, _, _ = _load("chain_gap")
    fixed = json.loads(json.dumps(bundle))
    fixed[2]["chain"]["parent_capsule_id"] = fixed[1]["capsule_id"]
    summary, _ = _run(fixed, witness)
    assert _stage(summary.stages, "Sequence").status == "pass"
    assert summary.finding is None


# ---------------------------------------------------------------------------
# witness_downgrade
# ---------------------------------------------------------------------------

def test_witness_downgrade_is_skip_not_fail():
    bundle, witness, _, _ = _load("witness_downgrade")
    summary, _ = _run(bundle, witness)
    for name in ("Integrity", "Sequence", "Authenticity"):
        assert _stage(summary.stages, name).status == "pass"
    w = _stage(summary.stages, "Witness")
    assert w.status == "skip"  # unreached witnesses are never disproven
    assert "1 of 3" in w.detail
    assert summary.finding is None


def test_witness_downgrade_upgrades_to_pass_when_all_report():
    bundle, _, _, _ = _load("witness_downgrade")
    summary, _ = _run(bundle, {"held": 3, "configured": 3, "reachable": True})
    assert _stage(summary.stages, "Witness").status == "pass"


# ---------------------------------------------------------------------------
# offline_pass
# ---------------------------------------------------------------------------

def test_offline_pass_verifies_locally_witness_skipped_not_failed():
    bundle, witness, _, _ = _load("offline_pass")
    summary, _ = _run(bundle, witness)
    for name in ("Integrity", "Sequence", "Authenticity"):
        assert _stage(summary.stages, name).status == "pass"
    w = _stage(summary.stages, "Witness")
    assert w.status == "skip"
    assert "unreachable" in w.detail
    assert summary.finding is None


# ---------------------------------------------------------------------------
# Authenticity is real crypto, not a fabricated flag — every fixture vector's
# Authenticity "pass" must depend on the embedded signature actually verifying.
# ---------------------------------------------------------------------------

def test_authenticity_mutant_check_flips_to_fail():
    import base64

    for name in ("digest_mismatch", "chain_gap", "witness_downgrade", "offline_pass"):
        bundle, _, _, _ = _load(name)
        tampered = json.loads(json.dumps(bundle))
        raw = bytearray(base64.b64decode(tampered[0]["signed_statement"]["statement_b64"]))
        raw[-1] ^= 0xFF  # flip the last byte — corrupts the COSE signature
        tampered[0]["signed_statement"]["statement_b64"] = base64.b64encode(bytes(raw)).decode()
        stage = aac._check_authenticity(tampered)
        assert stage.status == "fail", f"{name}: tampered signature must fail, not pass"


def test_authenticity_skip_when_no_signature_present():
    stage = aac._check_authenticity([{"capsule_id": "a1" * 32}])
    assert stage.status == "skip"
